source: source/
destination: compiled/

timezone: EST5EDT


sass:
  line_comments: true
  trace_selectors: false # supercedes `line_comments`
  debug_info: false # supercedes `line_comments` & `trace_selectors`
  sourcemap: file # Not working.  More info at: https://github.com/jekyll/jekyll-sass-converter/issues/12
  
  sass_dir: './'


collections:
  projects:
    output: true
    permalink: /p/:path.html


defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project